export const GET_ALL_POKEMONS = 'GET_ALL_POKEMONS';
export const GET_POKEMON_DETAIL = 'GET_POKEMON_DETAIL';
export const CLEAN_POKEMON_DETAIL = 'CLEAN_POKEMON_DETAIL';
export const FILTER = 'FILTER';
export const ORDER = 'ORDER';